"""removed parent_id from commitments

Revision ID: 08ed8376f1a1
Revises: 758b3d2b9d02
Create Date: 2026-08-02 10:53:11.740605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ed8376f1a1'
down_revision: Union[str, None] = '758b3d2b9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commitments_parent_id_fkey'), 'commitments', type_='foreignkey')
    op.drop_column('commitments', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('commitments_parent_id_fkey'), 'commitments', 'commitments', ['parent_id'], ['id'])
    # ### end Alembic commands ###
